import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'ta';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Comprehensive translation data
const translations = {
  en: {
    // Common
    'common.dashboard': 'Dashboard',
    'common.courses': 'Courses',
    'common.analytics': 'Analytics',
    'common.calendar': 'Calendar',
    'common.profile': 'Profile',
    'common.settings': 'Settings',
    'common.logout': 'Logout',
    'common.login': 'Login',
    'common.register': 'Register',
    'common.view': 'View',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.all': 'All',
    'common.title': 'Title',
    'common.description': 'Description',
    'common.language': 'Language',
    'common.settings': 'Settings',
    'common.todo': 'Todo',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.start': 'Start',
    'common.stop': 'Stop',
    'common.pause': 'Pause',
    'common.resume': 'Resume',
    'common.complete': 'Complete',
    'common.incomplete': 'Incomplete',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.public': 'Public',
    'common.private': 'Private',
    'common.draft': 'Draft',
    'common.published': 'Published',
    'common.pending': 'Pending',
    'common.approved': 'Approved',
    'common.rejected': 'Rejected',
    'common.all': 'All',
    'common.none': 'None',
    'common.select': 'Select',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.refresh': 'Refresh',
    'common.reset': 'Reset',
    'common.clear': 'Clear',
    'common.apply': 'Apply',
    'common.today': 'Today',
    'common.yesterday': 'Yesterday',
    'common.tomorrow': 'Tomorrow',
    'common.week': 'Week',
    'common.month': 'Month',
    'common.year': 'Year',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.duration': 'Duration',
    'common.status': 'Status',
    'common.type': 'Type',
    'common.category': 'Category',
    'common.description': 'Description',
    'common.title': 'Title',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.city': 'City',
    'common.country': 'Country',
    'common.language': 'Language',
    'common.theme': 'Theme',
    'common.notifications': 'Notifications',
    'common.messages': 'Messages',
    'common.help': 'Help',
    'common.support': 'Support',
    'common.about': 'About',
    'common.contact': 'Contact',
    'common.privacy': 'Privacy',
    'common.terms': 'Terms',
    'common.version': 'Version',
    
    // Auth
    'auth.welcome': 'Welcome to LMS',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.signOut': 'Sign Out',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.role': 'Role',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.resetPassword': 'Reset Password',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.rememberMe': 'Remember me',
    'auth.invalidCredentials': 'Invalid email or password',
    'auth.accountCreated': 'Account created successfully',
    'auth.passwordReset': 'Password reset link sent',
    'auth.loginSuccess': 'Login successful',
    'auth.logoutSuccess': 'Logout successful',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.overview': 'Overview',
    'dashboard.totalUsers': 'Total Users',
    'dashboard.activeCourses': 'Active Courses',
    'dashboard.completionRate': 'Completion Rate',
    'dashboard.revenue': 'Revenue',
    'dashboard.newSignups': 'New Signups',
    'dashboard.activeUsers': 'Active Users',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.statistics': 'Statistics',
    'dashboard.performance': 'Performance',
    'dashboard.trends': 'Trends',
    
    // Courses
    'courses.myCourses': 'My Courses',
    'courses.allCourses': 'All Courses',
    'courses.createCourse': 'Create Course',
    'courses.editCourse': 'Edit Course',
    'courses.deleteCourse': 'Delete Course',
    'courses.viewCourse': 'View Course',
    'courses.enrollCourse': 'Enroll in Course',
    'courses.unenrollCourse': 'Unenroll from Course',
    'courses.title': 'Course Title',
    'courses.description': 'Course Description',
    'courses.instructor': 'Instructor',
    'courses.duration': 'Duration',
    'courses.difficulty': 'Difficulty Level',
    'courses.enrollment': 'Enrollment',
    'courses.rating': 'Rating',
    'courses.beginner': 'Beginner',
    'courses.intermediate': 'Intermediate',
    'courses.advanced': 'Advanced',
    'courses.enrollCourse': 'Enroll in Course',
    
    // Profile
    'profile.editProfile': 'Edit Profile',
    'profile.updateProfile': 'Update Profile',
    'profile.updateSuccess': 'Profile updated successfully',
    'profile.avatar': 'Profile Picture',
    'profile.uploadAvatar': 'Upload Photo',
    'profile.removeAvatar': 'Remove Photo',
    'profile.personalInfo': 'Personal Information',
    'profile.changePassword': 'Change Password',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmNewPassword': 'Confirm New Password',
    
    // Calendar
    'calendar.myCalendar': 'My Calendar',
    'calendar.today': 'Today',
    'calendar.month': 'Month',
    'calendar.agenda': 'Agenda',
    'calendar.addEvent': 'Add Event',
    'calendar.editEvent': 'Edit Event',
    'calendar.eventTitle': 'Event Title',
    'calendar.eventDescription': 'Description',
    'calendar.eventDate': 'Date',
    'calendar.eventType': 'Type',
    'calendar.event': 'Event',
    'calendar.class': 'Class',
    'calendar.quiz': 'Quiz',
    'calendar.assignment': 'Assignment',
    'calendar.meeting': 'Meeting',
    'calendar.upcomingEvents': 'Upcoming Events',
    'calendar.noEvents': 'No upcoming events',
    
    // Errors
    'error.required': 'This field is required',
    'error.invalidEmail': 'Please enter a valid email address',
    'error.passwordTooShort': 'Password must be at least 6 characters',
    'error.passwordMismatch': 'Passwords do not match',
    'error.invalidFormat': 'Invalid file format',
    'error.fileTooLarge': 'File size too large (max 5MB)',
    'error.fileUpload': 'Failed to upload file',
    'error.general': 'An error occurred. Please try again.',
    'courses.beginner': 'Beginner',
    'courses.intermediate': 'Intermediate',
    'courses.advanced': 'Advanced',
    'courses.enrollCourse': 'Enroll',
    'courses.createCourse': 'Create Course',
    
    // Calendar
    'calendar.myCalendar': 'My Calendar',
    'calendar.today': 'Today',
    'calendar.addEvent': 'Add Event',
    'calendar.editEvent': 'Edit Event',
    'calendar.eventTitle': 'Event Title',
    'calendar.eventDescription': 'Description',
    'calendar.eventDate': 'Date',
    'calendar.eventType': 'Type',
    'calendar.upcomingEvents': 'Upcoming Events',
    'calendar.noEvents': 'No upcoming events',
    'calendar.month': 'Month',
    'calendar.agenda': 'Agenda',
    'calendar.event': 'Event',
    'calendar.class': 'Class',
    'calendar.quiz': 'Quiz',
    'calendar.assignment': 'Assignment',
    'calendar.meeting': 'Meeting',
    
    // Profile
    'profile.editProfile': 'Edit Profile',
    'profile.avatar': 'Profile Picture',
    'profile.uploadAvatar': 'Upload Photo',
    'profile.removeAvatar': 'Remove',
    'profile.personalInfo': 'Personal Information',
    'profile.changePassword': 'Change Password',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmNewPassword': 'Confirm New Password',
    'profile.updateProfile': 'Update Profile',
    'profile.updateSuccess': 'Profile updated successfully!',
    
    // Common
    'common.all': 'All',
    'common.view': 'View',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.title': 'Title',
    'common.description': 'Description',
    'common.language': 'Language',
    'common.todo': 'Todo',
    
    // Errors
    'error.required': 'This field is required',
    'error.invalidEmail': 'Please enter a valid email address',
    'error.passwordTooShort': 'Password must be at least 6 characters',
    'error.passwordMismatch': 'Passwords do not match',
    'error.general': 'An error occurred. Please try again.',
    'error.invalidFormat': 'Invalid file format',
    'error.fileTooLarge': 'File size too large (max 5MB)',
    'error.fileUpload': 'Failed to upload file',
    'courses.price': 'Price',
    'courses.category': 'Category',
    'courses.tags': 'Tags',
    'courses.thumbnail': 'Thumbnail',
    'courses.content': 'Course Content',
    'courses.lessons': 'Lessons',
    'courses.modules': 'Modules',
    'courses.progress': 'Progress',
    'courses.completed': 'Completed',
    'courses.inProgress': 'In Progress',
    'courses.notStarted': 'Not Started',
    'courses.beginner': 'Beginner',
    'courses.intermediate': 'Intermediate',
    'courses.advanced': 'Advanced',
    'courses.free': 'Free',
    'courses.paid': 'Paid',
    'courses.published': 'Published',
    'courses.draft': 'Draft',
    'courses.pending': 'Pending Approval',
    'courses.approved': 'Approved',
    'courses.rejected': 'Rejected',
    'courses.enrollmentSuccess': 'Successfully enrolled in course',
    'courses.enrollmentError': 'Failed to enroll in course',
    'courses.createSuccess': 'Course created successfully',
    'courses.updateSuccess': 'Course updated successfully',
    'courses.deleteSuccess': 'Course deleted successfully',
    'courses.deleteConfirm': 'Are you sure you want to delete this course?',
    
    // Quiz
    'quiz.myQuizzes': 'My Quizzes',
    'quiz.allQuizzes': 'All Quizzes',
    'quiz.createQuiz': 'Create Quiz',
    'quiz.editQuiz': 'Edit Quiz',
    'quiz.deleteQuiz': 'Delete Quiz',
    'quiz.startQuiz': 'Start Quiz',
    'quiz.submitQuiz': 'Submit Quiz',
    'quiz.retakeQuiz': 'Retake Quiz',
    'quiz.quizResults': 'Quiz Results',
    'quiz.questions': 'Questions',
    'quiz.timeLimit': 'Time Limit',
    'quiz.attempts': 'Attempts',
    'quiz.passingScore': 'Passing Score',
    'quiz.score': 'Score',
    'quiz.passed': 'Passed',
    'quiz.failed': 'Failed',
    'quiz.completed': 'Completed',
    'quiz.inProgress': 'In Progress',
    'quiz.notStarted': 'Not Started',
    'quiz.timeRemaining': 'Time Remaining',
    'quiz.question': 'Question',
    'quiz.answer': 'Answer',
    'quiz.correctAnswer': 'Correct Answer',
    'quiz.explanation': 'Explanation',
    'quiz.nextQuestion': 'Next Question',
    'quiz.previousQuestion': 'Previous Question',
    'quiz.reviewAnswers': 'Review Answers',
    'quiz.submitConfirm': 'Are you sure you want to submit the quiz?',
    
    // Users
    'users.allUsers': 'All Users',
    'users.createUser': 'Create User',
    'users.editUser': 'Edit User',
    'users.deleteUser': 'Delete User',
    'users.viewUser': 'View User',
    'users.activateUser': 'Activate User',
    'users.deactivateUser': 'Deactivate User',
    'users.firstName': 'First Name',
    'users.lastName': 'Last Name',
    'users.email': 'Email',
    'users.role': 'Role',
    'users.status': 'Status',
    'users.lastActive': 'Last Active',
    'users.joinedDate': 'Joined Date',
    'users.admin': 'Admin',
    'users.teacher': 'Teacher',
    'users.student': 'Student',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.online': 'Online',
    'users.offline': 'Offline',
    'users.createSuccess': 'User created successfully',
    'users.updateSuccess': 'User updated successfully',
    'users.deleteSuccess': 'User deleted successfully',
    'users.deleteConfirm': 'Are you sure you want to delete this user?',
    
    // Profile
    'profile.myProfile': 'My Profile',
    'profile.editProfile': 'Edit Profile',
    'profile.updateProfile': 'Update Profile',
    'profile.changePassword': 'Change Password',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmNewPassword': 'Confirm New Password',
    'profile.avatar': 'Profile Picture',
    'profile.uploadAvatar': 'Upload Avatar',
    'profile.removeAvatar': 'Remove Avatar',
    'profile.personalInfo': 'Personal Information',
    'profile.accountSettings': 'Account Settings',
    'profile.preferences': 'Preferences',
    'profile.updateSuccess': 'Profile updated successfully',
    'profile.passwordChanged': 'Password changed successfully',
    
    // Calendar
    'calendar.myCalendar': 'My Calendar',
    'calendar.addEvent': 'Add Event',
    'calendar.editEvent': 'Edit Event',
    'calendar.deleteEvent': 'Delete Event',
    'calendar.viewEvent': 'View Event',
    'calendar.eventTitle': 'Event Title',
    'calendar.eventDescription': 'Event Description',
    'calendar.eventDate': 'Event Date',
    'calendar.eventTime': 'Event Time',
    'calendar.eventType': 'Event Type',
    'calendar.allDay': 'All Day',
    'calendar.reminder': 'Reminder',
    'calendar.repeat': 'Repeat',
    'calendar.location': 'Location',
    'calendar.attendees': 'Attendees',
    'calendar.class': 'Class',
    'calendar.quiz': 'Quiz',
    'calendar.assignment': 'Assignment',
    'calendar.meeting': 'Meeting',
    'calendar.event': 'Event',
    'calendar.today': 'Today',
    'calendar.week': 'Week',
    'calendar.month': 'Month',
    'calendar.year': 'Year',
    'calendar.agenda': 'Agenda',
    'calendar.upcomingEvents': 'Upcoming Events',
    'calendar.noEvents': 'No events scheduled',
    'calendar.createSuccess': 'Event created successfully',
    'calendar.updateSuccess': 'Event updated successfully',
    'calendar.deleteSuccess': 'Event deleted successfully',
    'calendar.deleteConfirm': 'Are you sure you want to delete this event?',
    
    // Notifications
    'notifications.allNotifications': 'All Notifications',
    'notifications.markAsRead': 'Mark as Read',
    'notifications.markAllAsRead': 'Mark All as Read',
    'notifications.deleteNotification': 'Delete Notification',
    'notifications.clearAll': 'Clear All',
    'notifications.unread': 'Unread',
    'notifications.read': 'Read',
    'notifications.info': 'Info',
    'notifications.success': 'Success',
    'notifications.warning': 'Warning',
    'notifications.error': 'Error',
    'notifications.newCourse': 'New Course Available',
    'notifications.quizReminder': 'Quiz Reminder',
    'notifications.assignmentDue': 'Assignment Due',
    'notifications.gradePosted': 'Grade Posted',
    'notifications.messageReceived': 'Message Received',
    'notifications.courseCompleted': 'Course Completed',
    'notifications.certificateReady': 'Certificate Ready',
    'notifications.systemMaintenance': 'System Maintenance',
    'notifications.noNotifications': 'No notifications',
    'notifications.pushEnabled': 'Push notifications enabled',
    'notifications.pushDisabled': 'Push notifications disabled',
    
    // Messages
    'messages.allMessages': 'All Messages',
    'messages.newMessage': 'New Message',
    'messages.sendMessage': 'Send Message',
    'messages.replyMessage': 'Reply',
    'messages.forwardMessage': 'Forward',
    'messages.deleteMessage': 'Delete Message',
    'messages.markAsRead': 'Mark as Read',
    'messages.markAsUnread': 'Mark as Unread',
    'messages.searchMessages': 'Search Messages',
    'messages.recipient': 'Recipient',
    'messages.subject': 'Subject',
    'messages.message': 'Message',
    'messages.attachment': 'Attachment',
    'messages.sent': 'Sent',
    'messages.received': 'Received',
    'messages.draft': 'Draft',
    'messages.trash': 'Trash',
    'messages.inbox': 'Inbox',
    'messages.outbox': 'Outbox',
    'messages.compose': 'Compose',
    'messages.noMessages': 'No messages',
    'messages.sendSuccess': 'Message sent successfully',
    'messages.deleteSuccess': 'Message deleted successfully',
    
    // Analytics
    'analytics.overview': 'Analytics Overview',
    'analytics.userAnalytics': 'User Analytics',
    'analytics.courseAnalytics': 'Course Analytics',
    'analytics.quizAnalytics': 'Quiz Analytics',
    'analytics.performanceAnalytics': 'Performance Analytics',
    'analytics.engagementAnalytics': 'Engagement Analytics',
    'analytics.revenueAnalytics': 'Revenue Analytics',
    'analytics.exportReport': 'Export Report',
    'analytics.generateReport': 'Generate Report',
    'analytics.customReport': 'Custom Report',
    'analytics.dateRange': 'Date Range',
    'analytics.lastWeek': 'Last Week',
    'analytics.lastMonth': 'Last Month',
    'analytics.lastQuarter': 'Last Quarter',
    'analytics.lastYear': 'Last Year',
    'analytics.customRange': 'Custom Range',
    
    // Certificates
    'certificates.myCertificates': 'My Certificates',
    'certificates.allCertificates': 'All Certificates',
    'certificates.viewCertificate': 'View Certificate',
    'certificates.downloadCertificate': 'Download Certificate',
    'certificates.shareCertificate': 'Share Certificate',
    'certificates.verifyCertificate': 'Verify Certificate',
    'certificates.certificateId': 'Certificate ID',
    'certificates.issuedDate': 'Issued Date',
    'certificates.expiryDate': 'Expiry Date',
    'certificates.issuer': 'Issuer',
    'certificates.recipient': 'Recipient',
    'certificates.course': 'Course',
    'certificates.grade': 'Grade',
    'certificates.valid': 'Valid',
    'certificates.expired': 'Expired',
    'certificates.revoked': 'Revoked',
    'certificates.noCertificates': 'No certificates available',
    
    // Settings
    'settings.generalSettings': 'General Settings',
    'settings.accountSettings': 'Account Settings',
    'settings.privacySettings': 'Privacy Settings',
    'settings.notificationSettings': 'Notification Settings',
    'settings.languageSettings': 'Language Settings',
    'settings.themeSettings': 'Theme Settings',
    'settings.securitySettings': 'Security Settings',
    'settings.systemSettings': 'System Settings',
    'settings.saveSettings': 'Save Settings',
    'settings.resetSettings': 'Reset Settings',
    'settings.exportSettings': 'Export Settings',
    'settings.importSettings': 'Import Settings',
    'settings.lightMode': 'Light Mode',
    'settings.darkMode': 'Dark Mode',
    'settings.autoMode': 'Auto Mode',
    'settings.emailNotifications': 'Email Notifications',
    'settings.pushNotifications': 'Push Notifications',
    'settings.smsNotifications': 'SMS Notifications',
    'settings.twoFactorAuth': 'Two-Factor Authentication',
    'settings.sessionTimeout': 'Session Timeout',
    'settings.dataRetention': 'Data Retention',
    'settings.privacyMode': 'Privacy Mode',
    'settings.publicProfile': 'Public Profile',
    'settings.showOnlineStatus': 'Show Online Status',
    'settings.allowMessages': 'Allow Messages',
    'settings.settingsUpdated': 'Settings updated successfully',
    
    // Errors
    'error.general': 'An error occurred',
    'error.network': 'Network error',
    'error.server': 'Server error',
    'error.notFound': 'Not found',
    'error.unauthorized': 'Unauthorized',
    'error.forbidden': 'Forbidden',
    'error.validation': 'Validation error',
    'error.timeout': 'Request timeout',
    'error.fileUpload': 'File upload error',
    'error.fileTooLarge': 'File too large',
    'error.invalidFormat': 'Invalid format',
    'error.required': 'This field is required',
    'error.invalidEmail': 'Invalid email address',
    'error.passwordTooShort': 'Password too short',
    'error.passwordMismatch': 'Passwords do not match',
    'error.tryAgain': 'Please try again',
    'error.contactSupport': 'Please contact support',
    
    // Success Messages
    'success.saved': 'Saved successfully',
    'success.updated': 'Updated successfully',
    'success.deleted': 'Deleted successfully',
    'success.created': 'Created successfully',
    'success.uploaded': 'Uploaded successfully',
    'success.downloaded': 'Downloaded successfully',
    'success.sent': 'Sent successfully',
    'success.completed': 'Completed successfully',
    'success.enrolled': 'Enrolled successfully',
    'success.unenrolled': 'Unenrolled successfully',
    'success.activated': 'Activated successfully',
    'success.deactivated': 'Deactivated successfully',
    'success.verified': 'Verified successfully',
    'success.published': 'Published successfully',
    'success.unpublished': 'Unpublished successfully',
  },
  hi: {
    // Common
    'common.dashboard': 'डैशबोर्ड',
    'common.courses': 'कोर्स',
    'common.analytics': 'एनालिटिक्स',
    'common.calendar': 'कैलेंडर',
    'common.profile': 'प्रोफ़ाइल',
    'common.settings': 'सेटिंग्स',
    'common.logout': 'लॉगआउट',
    'common.login': 'लॉगिन',
    'common.register': 'रजिस्टर',
    'common.save': 'सेव करें',
    'common.cancel': 'रद्द करें',
    'common.submit': 'जमा करें',
    'common.loading': 'लोड हो रहा है...',
    'common.search': 'खोजें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.view': 'देखें',
    'common.create': 'बनाएं',
    'common.update': 'अपडेट करें',
    'common.add': 'जोड़ें',
    'common.remove': 'हटाएं',
    'common.yes': 'हाँ',
    'common.no': 'नहीं',
    'common.confirm': 'पुष्टि करें',
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.previous': 'पिछला',
    'common.close': 'बंद करें',
    'common.open': 'खोलें',
    'common.start': 'शुरू करें',
    'common.stop': 'रोकें',
    'common.pause': 'रोकें',
    'common.resume': 'फिर से शुरू करें',
    'common.complete': 'पूरा करें',
    'common.incomplete': 'अधूरा',
    'common.active': 'सक्रिय',
    'common.inactive': 'निष्क्रिय',
    'common.enabled': 'सक्षम',
    'common.disabled': 'अक्षम',
    'common.public': 'सार्वजनिक',
    'common.private': 'निजी',
    'common.draft': 'मसौदा',
    'common.published': 'प्रकाशित',
    'common.pending': 'लंबित',
    'common.approved': 'अनुमोदित',
    'common.rejected': 'अस्वीकृत',
    'common.all': 'सभी',
    'common.none': 'कोई नहीं',
    'common.select': 'चुनें',
    'common.upload': 'अपलोड करें',
    'common.download': 'डाउनलोड करें',
    'common.export': 'निर्यात करें',
    'common.import': 'आयात करें',
    'common.filter': 'फ़िल्टर',
    'common.sort': 'क्रमबद्ध करें',
    'common.refresh': 'रीफ्रेश करें',
    'common.reset': 'रीसेट करें',
    'common.clear': 'साफ़ करें',
    'common.apply': 'लागू करें',
    'common.today': 'आज',
    'common.yesterday': 'कल',
    'common.tomorrow': 'कल',
    'common.week': 'सप्ताह',
    'common.month': 'महीना',
    'common.year': 'साल',
    'common.date': 'तारीख',
    'common.time': 'समय',
    'common.duration': 'अवधि',
    'common.status': 'स्थिति',
    'common.type': 'प्रकार',
    'common.category': 'श्रेणी',
    'common.description': 'विवरण',
    'common.title': 'शीर्षक',
    'common.name': 'नाम',
    'common.email': 'ईमेल',
    'common.phone': 'फोन',
    'common.address': 'पता',
    'common.city': 'शहर',
    'common.country': 'देश',
    'common.language': 'भाषा',
    'common.theme': 'थीम',
    'common.notifications': 'सूचनाएं',
    'common.messages': 'संदेश',
    'common.help': 'सहायता',
    'common.support': 'समर्थन',
    'common.about': 'के बारे में',
    'common.contact': 'संपर्क',
    'common.privacy': 'गोपनीयता',
    'common.terms': 'नियम',
    'common.version': 'संस्करण',
    
    // Auth
    'auth.welcome': 'LMS में आपका स्वागत है',
    'auth.signIn': 'साइन इन करें',
    'auth.signUp': 'साइन अप करें',
    'auth.signOut': 'साइन आउट करें',
    'auth.email': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.confirmPassword': 'पासवर्ड की पुष्टि करें',
    'auth.firstName': 'पहला नाम',
    'auth.lastName': 'अंतिम नाम',
    'auth.role': 'भूमिका',
    'auth.forgotPassword': 'पासवर्ड भूल गए?',
    'auth.resetPassword': 'पासवर्ड रीसेट करें',
    'auth.noAccount': 'खाता नहीं है?',
    'auth.hasAccount': 'पहले से खाता है?',
    'auth.rememberMe': 'मुझे याद रखें',
    'auth.invalidCredentials': 'अमान्य ईमेल या पासवर्ड',
    'auth.accountCreated': 'खाता सफलतापूर्वक बनाया गया',
    'auth.passwordReset': 'पासवर्ड रीसेट लिंक भेजा गया',
    'auth.loginSuccess': 'लॉगिन सफल',
    'auth.logoutSuccess': 'लॉगआउट सफल',
    
    // Dashboard
    'dashboard.welcome': 'वापसी पर स्वागत है',
    'dashboard.overview': 'अवलोकन',
    'dashboard.totalUsers': 'कुल उपयोगकर्ता',
    'dashboard.activeCourses': 'सक्रिय कोर्स',
    'dashboard.completionRate': 'पूर्णता दर',
    'dashboard.revenue': 'राजस्व',
    'dashboard.newSignups': 'नए साइनअप',
    'dashboard.activeUsers': 'सक्रिय उपयोगकर्ता',
    'dashboard.recentActivity': 'हाल की गतिविधि',
    'dashboard.quickActions': 'त्वरित कार्य',
    'dashboard.statistics': 'आंकड़े',
    'dashboard.performance': 'प्रदर्शन',
    'dashboard.trends': 'रुझान',
    
    // Courses
    'courses.myCourses': 'मेरे कोर्स',
    'courses.allCourses': 'सभी कोर्स',
    'courses.createCourse': 'कोर्स बनाएं',
    'courses.editCourse': 'कोर्स संपादित करें',
    'courses.deleteCourse': 'कोर्स हटाएं',
    'courses.viewCourse': 'कोर्स देखें',
    'courses.enrollCourse': 'कोर्स में दाखिला लें',
    'courses.unenrollCourse': 'कोर्स से निकलें',
    'courses.title': 'कोर्स शीर्षक',
    'courses.description': 'कोर्स विवरण',
    'courses.instructor': 'प्रशिक्षक',
    'courses.duration': 'अवधि',
    'courses.difficulty': 'कठिनाई स्तर',
    'courses.enrollment': 'नामांकन',
    'courses.rating': 'रेटिंग',
    'courses.beginner': 'शुरुआती',
    'courses.intermediate': 'मध्यम',
    'courses.advanced': 'उन्नत',
    'courses.enrollCourse': 'नामांकन करें',
    'courses.createCourse': 'कोर्स बनाएं',
    
    // Calendar
    'calendar.myCalendar': 'मेरा कैलेंडर',
    'calendar.today': 'आज',
    'calendar.addEvent': 'इवेंट जोड़ें',
    'calendar.editEvent': 'इवेंट संपादित करें',
    'calendar.eventTitle': 'इवेंट शीर्षक',
    'calendar.eventDescription': 'विवरण',
    'calendar.eventDate': 'तारीख',
    'calendar.eventType': 'प्रकार',
    'calendar.upcomingEvents': 'आगामी इवेंट्स',
    'calendar.noEvents': 'कोई आगामी इवेंट नहीं',
    'calendar.month': 'महीना',
    'calendar.agenda': 'एजेंडा',
    'calendar.event': 'इवेंट',
    'calendar.class': 'क्लास',
    'calendar.quiz': 'क्विज़',
    'calendar.assignment': 'असाइनमेंट',
    'calendar.meeting': 'मीटिंग',
    
    // Profile
    'profile.editProfile': 'प्रोफ़ाइल संपादित करें',
    'profile.avatar': 'प्रोफ़ाइल चित्र',
    'profile.uploadAvatar': 'फोटो अपलोड करें',
    'profile.removeAvatar': 'हटाएं',
    'profile.personalInfo': 'व्यक्तिगत जानकारी',
    'profile.changePassword': 'पासवर्ड बदलें',
    'profile.currentPassword': 'वर्तमान पासवर्ड',
    'profile.newPassword': 'नया पासवर्ड',
    'profile.confirmNewPassword': 'नया पासवर्ड पुष्टि करें',
    'profile.updateProfile': 'प्रोफ़ाइल अपडेट करें',
    'profile.updateSuccess': 'प्रोफ़ाइल सफलतापूर्वक अपडेट हो गया!',
    
    // Common
    'common.all': 'सभी',
    'common.view': 'देखें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.create': 'बनाएं',
    'common.update': 'अपडेट करें',
    'common.title': 'शीर्षक',
    'common.description': 'विवरण',
    'common.language': 'भाषा',
    'common.todo': 'कार्य',
    
    // Errors
    'error.required': 'यह फ़ील्ड आवश्यक है',
    'error.invalidEmail': 'कृपया एक वैध ईमेल पता दर्ज करें',
    'error.passwordTooShort': 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
    'error.passwordMismatch': 'पासवर्ड मेल नहीं खाते',
    'error.general': 'एक त्रुटि हुई। कृपया पुनः प्रयास करें।',
    'error.invalidFormat': 'अमान्य फ़ाइल प्रारूप',
    'error.fileTooLarge': 'फ़ाइल का आकार बहुत बड़ा है (अधिकतम 5MB)',
    'error.fileUpload': 'फ़ाइल अपलोड करने में विफल',
    'courses.price': 'मूल्य',
    'courses.category': 'श्रेणी',
    'courses.tags': 'टैग',
    'courses.thumbnail': 'थंबनेल',
    'courses.content': 'कोर्स सामग्री',
    'courses.lessons': 'पाठ',
    'courses.modules': 'मॉड्यूल',
    'courses.progress': 'प्रगति',
    'courses.completed': 'पूर्ण',
    'courses.inProgress': 'प्रगति में',
    'courses.notStarted': 'शुरू नहीं हुआ',
    'courses.beginner': 'शुरुआती',
    'courses.intermediate': 'मध्यम',
    'courses.advanced': 'उन्नत',
    'courses.free': 'मुफ्त',
    'courses.paid': 'भुगतान',
    'courses.published': 'प्रकाशित',
    'courses.draft': 'मसौदा',
    'courses.pending': 'अनुमोदन लंबित',
    'courses.approved': 'अनुमोदित',
    'courses.rejected': 'अस्वीकृत',
    'courses.enrollmentSuccess': 'कोर्स में सफलतापूर्वक दाखिला लिया गया',
    'courses.enrollmentError': 'कोर्स में दाखिला लेने में विफल',
    'courses.createSuccess': 'कोर्स सफलतापूर्वक बनाया गया',
    'courses.updateSuccess': 'कोर्स सफलतापूर्वक अपडेट किया गया',
    'courses.deleteSuccess': 'कोर्स सफलतापूर्वक हटाया गया',
    'courses.deleteConfirm': 'क्या आप वाकई इस कोर्स को हटाना चाहते हैं?',
    
    // Quiz
    'quiz.myQuizzes': 'मेरी क्विज़',
    'quiz.allQuizzes': 'सभी क्विज़',
    'quiz.createQuiz': 'क्विज़ बनाएं',
    'quiz.editQuiz': 'क्विज़ संपादित करें',
    'quiz.deleteQuiz': 'क्विज़ हटाएं',
    'quiz.startQuiz': 'क्विज़ शुरू करें',
    'quiz.submitQuiz': 'क्विज़ जमा करें',
    'quiz.retakeQuiz': 'क्विज़ फिर से लें',
    'quiz.quizResults': 'क्विज़ परिणाम',
    'quiz.questions': 'प्रश्न',
    'quiz.timeLimit': 'समय सीमा',
    'quiz.attempts': 'प्रयास',
    'quiz.passingScore': 'उत्तीर्ण अंक',
    'quiz.score': 'अंक',
    'quiz.passed': 'उत्तीर्ण',
    'quiz.failed': 'असफल',
    'quiz.completed': 'पूर्ण',
    'quiz.inProgress': 'प्रगति में',
    'quiz.notStarted': 'शुरू नहीं हुआ',
    'quiz.timeRemaining': 'शेष समय',
    'quiz.question': 'प्रश्न',
    'quiz.answer': 'उत्तर',
    'quiz.correctAnswer': 'सही उत्तर',
    'quiz.explanation': 'व्याख्या',
    'quiz.nextQuestion': 'अगला प्रश्न',
    'quiz.previousQuestion': 'पिछला प्रश्न',
    'quiz.reviewAnswers': 'उत्तरों की समीक्षा करें',
    'quiz.submitConfirm': 'क्या आप वाकई क्विज़ जमा करना चाहते हैं?',
    
    // Users
    'users.allUsers': 'सभी उपयोगकर्ता',
    'users.createUser': 'उपयोगकर्ता बनाएं',
    'users.editUser': 'उपयोगकर्ता संपादित करें',
    'users.deleteUser': 'उपयोगकर्ता हटाएं',
    'users.viewUser': 'उपयोगकर्ता देखें',
    'users.activateUser': 'उपयोगकर्ता सक्रिय करें',
    'users.deactivateUser': 'उपयोगकर्ता निष्क्रिय करें',
    'users.firstName': 'पहला नाम',
    'users.lastName': 'अंतिम नाम',
    'users.email': 'ईमेल',
    'users.role': 'भूमिका',
    'users.status': 'स्थिति',
    'users.lastActive': 'अंतिम सक्रिय',
    'users.joinedDate': 'शामिल होने की तारीख',
    'users.admin': 'व्यवस्थापक',
    'users.teacher': 'शिक्षक',
    'users.student': 'छात्र',
    'users.active': 'सक्रिय',
    'users.inactive': 'निष्क्रिय',
    'users.online': 'ऑनलाइन',
    'users.offline': 'ऑफलाइन',
    'users.createSuccess': 'उपयोगकर्ता सफलतापूर्वक बनाया गया',
    'users.updateSuccess': 'उपयोगकर्ता सफलतापूर्वक अपडेट किया गया',
    'users.deleteSuccess': 'उपयोगकर्ता सफलतापूर्वक हटाया गया',
    'users.deleteConfirm': 'क्या आप वाकई इस उपयोगकर्ता को हटाना चाहते हैं?',
    
    // Profile
    'profile.myProfile': 'मेरी प्रोफ़ाइल',
    'profile.editProfile': 'प्रोफ़ाइल संपादित करें',
    'profile.updateProfile': 'प्रोफ़ाइल अपडेट करें',
    'profile.changePassword': 'पासवर्ड बदलें',
    'profile.currentPassword': 'वर्तमान पासवर्ड',
    'profile.newPassword': 'नया पासवर्ड',
    'profile.confirmNewPassword': 'नए पासवर्ड की पुष्टि करें',
    'profile.avatar': 'प्रोफ़ाइल चित्र',
    'profile.uploadAvatar': 'अवतार अपलोड करें',
    'profile.removeAvatar': 'अवतार हटाएं',
    'profile.personalInfo': 'व्यक्तिगत जानकारी',
    'profile.accountSettings': 'खाता सेटिंग्स',
    'profile.preferences': 'प्राथमिकताएं',
    'profile.updateSuccess': 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई',
    'profile.passwordChanged': 'पासवर्ड सफलतापूर्वक बदला गया',
    
    // Calendar
    'calendar.myCalendar': 'मेरा कैलेंडर',
    'calendar.addEvent': 'इवेंट जोड़ें',
    'calendar.editEvent': 'इवेंट संपादित करें',
    'calendar.deleteEvent': 'इवेंट हटाएं',
    'calendar.viewEvent': 'इवेंट देखें',
    'calendar.eventTitle': 'इवेंट शीर्षक',
    'calendar.eventDescription': 'इवेंट विवरण',
    'calendar.eventDate': 'इवेंट तारीख',
    'calendar.eventTime': 'इवेंट समय',
    'calendar.eventType': 'इवेंट प्रकार',
    'calendar.allDay': 'पूरा दिन',
    'calendar.reminder': 'अनुस्मारक',
    'calendar.repeat': 'दोहराएं',
    'calendar.location': 'स्थान',
    'calendar.attendees': 'उपस्थित लोग',
    'calendar.class': 'कक्षा',
    'calendar.quiz': 'क्विज़',
    'calendar.assignment': 'असाइनमेंट',
    'calendar.meeting': 'बैठक',
    'calendar.event': 'इवेंट',
    'calendar.today': 'आज',
    'calendar.week': 'सप्ताह',
    'calendar.month': 'महीना',
    'calendar.year': 'साल',
    'calendar.agenda': 'एजेंडा',
    'calendar.upcomingEvents': 'आगामी इवेंट्स',
    'calendar.noEvents': 'कोई इवेंट निर्धारित नहीं',
    'calendar.createSuccess': 'इवेंट सफलतापूर्वक बनाया गया',
    'calendar.updateSuccess': 'इवेंट सफलतापूर्वक अपडेट किया गया',
    'calendar.deleteSuccess': 'इवेंट सफलतापूर्वक हटाया गया',
    'calendar.deleteConfirm': 'क्या आप वाकई इस इवेंट को हटाना चाहते हैं?',
    
    // Notifications
    'notifications.allNotifications': 'सभी सूचनाएं',
    'notifications.markAsRead': 'पढ़ा हुआ चिह्नित करें',
    'notifications.markAllAsRead': 'सभी को पढ़ा हुआ चिह्नित करें',
    'notifications.deleteNotification': 'सूचना हटाएं',
    'notifications.clearAll': 'सभी साफ़ करें',
    'notifications.unread': 'अपठित',
    'notifications.read': 'पढ़ा हुआ',
    'notifications.info': 'जानकारी',
    'notifications.success': 'सफलता',
    'notifications.warning': 'चेतावनी',
    'notifications.error': 'त्रुटि',
    'notifications.newCourse': 'नया कोर्स उपलब्ध',
    'notifications.quizReminder': 'क्विज़ अनुस्मारक',
    'notifications.assignmentDue': 'असाइनमेंट देय',
    'notifications.gradePosted': 'ग्रेड पोस्ट किया गया',
    'notifications.messageReceived': 'संदेश प्राप्त हुआ',
    'notifications.courseCompleted': 'कोर्स पूरा हुआ',
    'notifications.certificateReady': 'प्रमाणपत्र तैयार',
    'notifications.systemMaintenance': 'सिस्टम रखरखाव',
    'notifications.noNotifications': 'कोई सूचना नहीं',
    'notifications.pushEnabled': 'पुश सूचनाएं सक्षम',
    'notifications.pushDisabled': 'पुश सूचनाएं अक्षम',
    
    // Messages
    'messages.allMessages': 'सभी संदेश',
    'messages.newMessage': 'नया संदेश',
    'messages.sendMessage': 'संदेश भेजें',
    'messages.replyMessage': 'जवाब दें',
    'messages.forwardMessage': 'आगे भेजें',
    'messages.deleteMessage': 'संदेश हटाएं',
    'messages.markAsRead': 'पढ़ा हुआ चिह्नित करें',
    'messages.markAsUnread': 'अपठित चिह्नित करें',
    'messages.searchMessages': 'संदेश खोजें',
    'messages.recipient': 'प्राप्तकर्ता',
    'messages.subject': 'विषय',
    'messages.message': 'संदेश',
    'messages.attachment': 'अनुलग्नक',
    'messages.sent': 'भेजा गया',
    'messages.received': 'प्राप्त',
    'messages.draft': 'मसौदा',
    'messages.trash': 'कूड़ादान',
    'messages.inbox': 'इनबॉक्स',
    'messages.outbox': 'आउटबॉक्स',
    'messages.compose': 'लिखें',
    'messages.noMessages': 'कोई संदेश नहीं',
    'messages.sendSuccess': 'संदेश सफलतापूर्वक भेजा गया',
    'messages.deleteSuccess': 'संदेश सफलतापूर्वक हटाया गया',
    
    // Analytics
    'analytics.overview': 'एनालिटिक्स अवलोकन',
    'analytics.userAnalytics': 'उपयोगकर्ता एनालिटिक्स',
    'analytics.courseAnalytics': 'कोर्स एनालिटिक्स',
    'analytics.quizAnalytics': 'क्विज़ एनालिटिक्स',
    'analytics.performanceAnalytics': 'प्रदर्शन एनालिटिक्स',
    'analytics.engagementAnalytics': 'सहभागिता एनालिटिक्स',
    'analytics.revenueAnalytics': 'राजस्व एनालिटिक्स',
    'analytics.exportReport': 'रिपोर्ट निर्यात करें',
    'analytics.generateReport': 'रिपोर्ट जेनरेट करें',
    'analytics.customReport': 'कस्टम रिपोर्ट',
    'analytics.dateRange': 'तारीख सीमा',
    'analytics.lastWeek': 'पिछला सप्ताह',
    'analytics.lastMonth': 'पिछला महीना',
    'analytics.lastQuarter': 'पिछली तिमाही',
    'analytics.lastYear': 'पिछला साल',
    'analytics.customRange': 'कस्टम सीमा',
    
    // Certificates
    'certificates.myCertificates': 'मेरे प्रमाणपत्र',
    'certificates.allCertificates': 'सभी प्रमाणपत्र',
    'certificates.viewCertificate': 'प्रमाणपत्र देखें',
    'certificates.downloadCertificate': 'प्रमाणपत्र डाउनलोड करें',
    'certificates.shareCertificate': 'प्रमाणपत्र साझा करें',
    'certificates.verifyCertificate': 'प्रमाणपत्र सत्यापित करें',
    'certificates.certificateId': 'प्रमाणपत्र आईडी',
    'certificates.issuedDate': 'जारी तारीख',
    'certificates.expiryDate': 'समाप्ति तारीख',
    'certificates.issuer': 'जारीकर्ता',
    'certificates.recipient': 'प्राप्तकर्ता',
    'certificates.course': 'कोर्स',
    'certificates.grade': 'ग्रेड',
    'certificates.valid': 'वैध',
    'certificates.expired': 'समाप्त',
    'certificates.revoked': 'रद्द',
    'certificates.noCertificates': 'कोई प्रमाणपत्र उपलब्ध नहीं',
    
    // Settings
    'settings.generalSettings': 'सामान्य सेटिंग्स',
    'settings.accountSettings': 'खाता सेटिंग्स',
    'settings.privacySettings': 'गोपनीयता सेटिंग्स',
    'settings.notificationSettings': 'सूचना सेटिंग्स',
    'settings.languageSettings': 'भाषा सेटिंग्स',
    'settings.themeSettings': 'थीम सेटिंग्स',
    'settings.securitySettings': 'सुरक्षा सेटिंग्स',
    'settings.systemSettings': 'सिस्टम सेटिंग्स',
    'settings.saveSettings': 'सेटिंग्स सेव करें',
    'settings.resetSettings': 'सेटिंग्स रीसेट करें',
    'settings.exportSettings': 'सेटिंग्स निर्यात करें',
    'settings.importSettings': 'सेटिंग्स आयात करें',
    'settings.lightMode': 'लाइट मोड',
    'settings.darkMode': 'डार्क मोड',
    'settings.autoMode': 'ऑटो मोड',
    'settings.emailNotifications': 'ईमेल सूचनाएं',
    'settings.pushNotifications': 'पुश सूचनाएं',
    'settings.smsNotifications': 'SMS सूचनाएं',
    'settings.twoFactorAuth': 'दो-कारक प्रमाणीकरण',
    'settings.sessionTimeout': 'सत्र समय समाप्ति',
    'settings.dataRetention': 'डेटा प्रतिधारण',
    'settings.privacyMode': 'गोपनीयता मोड',
    'settings.publicProfile': 'सार्वजनिक प्रोफ़ाइल',
    'settings.showOnlineStatus': 'ऑनलाइन स्थिति दिखाएं',
    'settings.allowMessages': 'संदेशों की अनुमति दें',
    'settings.settingsUpdated': 'सेटिंग्स सफलतापूर्वक अपडेट की गईं',
    
    // Errors
    'error.general': 'एक त्रुटि हुई',
    'error.network': 'नेटवर्क त्रुटि',
    'error.server': 'सर्वर त्रुटि',
    'error.notFound': 'नहीं मिला',
    'error.unauthorized': 'अनधिकृत',
    'error.forbidden': 'निषिद्ध',
    'error.validation': 'सत्यापन त्रुटि',
    'error.timeout': 'अनुरोध समय समाप्त',
    'error.fileUpload': 'फ़ाइल अपलोड त्रुटि',
    'error.fileTooLarge': 'फ़ाइल बहुत बड़ी',
    'error.invalidFormat': 'अमान्य प्रारूप',
    'error.required': 'यह फ़ील्ड आवश्यक है',
    'error.invalidEmail': 'अमान्य ईमेल पता',
    'error.passwordTooShort': 'पासवर्ड बहुत छोटा',
    'error.passwordMismatch': 'पासवर्ड मेल नहीं खाते',
    'error.tryAgain': 'कृपया पुनः प्रयास करें',
    'error.contactSupport': 'कृपया समर्थन से संपर्क करें',
    
    // Success Messages
    'success.saved': 'सफलतापूर्वक सेव किया गया',
    'success.updated': 'सफलतापूर्वक अपडेट किया गया',
    'success.deleted': 'सफलतापूर्वक हटाया गया',
    'success.created': 'सफलतापूर्वक बनाया गया',
    'success.uploaded': 'सफलतापूर्वक अपलोड किया गया',
    'success.downloaded': 'सफलतापूर्वक डाउनलोड किया गया',
    'success.sent': 'सफलतापूर्वक भेजा गया',
    'success.completed': 'सफलतापूर्वक पूरा किया गया',
    'success.enrolled': 'सफलतापूर्वक दाखिला लिया गया',
    'success.unenrolled': 'सफलतापूर्वक निकाला गया',
    'success.activated': 'सफलतापूर्वक सक्रिय किया गया',
    'success.deactivated': 'सफलतापूर्वक निष्क्रिय किया गया',
    'success.verified': 'सफलतापूर्वक सत्यापित किया गया',
    'success.published': 'सफलतापूर्वक प्रकाशित किया गया',
    'success.unpublished': 'सफलतापूर्वक अप्रकाशित किया गया',
  },
  ta: {
    // Common
    'common.dashboard': 'டாஷ்போர்டு',
    'common.courses': 'பாடங்கள்',
    'common.analytics': 'பகுப்பாய்வு',
    'common.calendar': 'காலெண்டர்',
    'common.profile': 'சுயவிவரம்',
    'common.settings': 'அமைப்புகள்',
    'common.logout': 'வெளியேறு',
    'common.login': 'உள்நுழைய',
    'common.register': 'பதிவு செய்க',
    'common.save': 'சேமி',
    'common.cancel': 'ரத்து செய்',
    'common.submit': 'சமர்ப்பி',
    'common.loading': 'ஏற்றுகிறது...',
    'common.search': 'தேடு',
    'common.edit': 'திருத்து',
    'common.delete': 'நீக்கு',
    'common.view': 'பார்',
    'common.create': 'உருவாக்கு',
    'common.update': 'புதுப்பி',
    'common.add': 'சேர்',
    'common.remove': 'நீக்கு',
    'common.yes': 'ஆம்',
    'common.no': 'இல்லை',
    'common.confirm': 'உறுதிப்படுத்து',
    'common.back': 'பின்',
    'common.next': 'அடுத்து',
    'common.previous': 'முந்தைய',
    'common.close': 'மூடு',
    'common.open': 'திற',
    'common.start': 'தொடங்கு',
    'common.stop': 'நிறுத்து',
    'common.pause': 'இடைநிறுத்து',
    'common.resume': 'மீண்டும் தொடங்கு',
    'common.complete': 'முடி',
    'common.incomplete': 'முழுமையற்ற',
    'common.active': 'செயலில்',
    'common.inactive': 'செயலற்ற',
    'common.enabled': 'இயக்கப்பட்ட',
    'common.disabled': 'முடக்கப்பட்ட',
    'common.public': 'பொது',
    'common.private': 'தனிப்பட்ட',
    'common.draft': 'வரைவு',
    'common.published': 'வெளியிடப்பட்ட',
    'common.pending': 'நிலுவையில்',
    'common.approved': 'அங்கீகரிக்கப்பட்ட',
    'common.rejected': 'நிராகரிக்கப்பட்ட',
    'common.all': 'அனைத்தும்',
    'common.none': 'எதுவும் இல்லை',
    'common.select': 'தேர்ந்தெடு',
    'common.upload': 'பதிவேற்று',
    'common.download': 'பதிவிறக்கு',
    'common.export': 'ஏற்றுமதி',
    'common.import': 'இறக்குமதி',
    'common.filter': 'வடிகட்டு',
    'common.sort': 'வரிசைப்படுத்து',
    'common.refresh': 'புதுப்பி',
    'common.reset': 'மீட்டமை',
    'common.clear': 'அழி',
    'common.apply': 'பயன்படுத்து',
    'common.today': 'இன்று',
    'common.yesterday': 'நேற்று',
    'common.tomorrow': 'நாளை',
    'common.week': 'வாரம்',
    'common.month': 'மாதம்',
    'common.year': 'ஆண்டு',
    'common.date': 'தேதி',
    'common.time': 'நேரம்',
    'common.duration': 'காலம்',
    'common.status': 'நிலை',
    'common.type': 'வகை',
    'common.category': 'பிரிவு',
    'common.description': 'விளக்கம்',
    'common.title': 'தலைப்பு',
    'common.name': 'பெயர்',
    'common.email': 'மின்னஞ்சல்',
    'common.phone': 'தொலைபேசி',
    'common.address': 'முகவரி',
    'common.city': 'நகரம்',
    'common.country': 'நாடு',
    'common.language': 'மொழி',
    'common.theme': 'தீம்',
    'common.notifications': 'அறிவிப்புகள்',
    'common.messages': 'செய்திகள்',
    'common.help': 'உதவி',
    'common.support': 'ஆதரவு',
    'common.about': 'பற்றி',
    'common.contact': 'தொடர்பு',
    'common.privacy': 'தனியுரிமை',
    'common.terms': 'விதிமுறைகள்',
    'common.version': 'பதிப்பு',
    
    // Auth
    'auth.welcome': 'LMS இல் வரவேற்கிறோம்',
    'auth.signIn': 'உள்நுழைய',
    'auth.signUp': 'பதிவு செய்க',
    'auth.signOut': 'வெளியேறு',
    'auth.email': 'மின்னஞ்சல் முகவரி',
    'auth.password': 'கடவுச்சொல்',
    'auth.confirmPassword': 'கடவுச்சொல்லை உறுதிப்படுத்து',
    'auth.firstName': 'முதல் பெயர்',
    'auth.lastName': 'கடைசி பெயர்',
    'auth.role': 'பாத்திரம்',
    'auth.forgotPassword': 'கடவுச்சொல் மறந்துவிட்டதா?',
    'auth.resetPassword': 'கடவுச்சொல்லை மீட்டமை',
    'auth.noAccount': 'கணக்கு இல்லையா?',
    'auth.hasAccount': 'ஏற்கனவே கணக்கு உள்ளதா?',
    'auth.rememberMe': 'என்னை நினைவில் வைத்துக்கொள்',
    'auth.invalidCredentials': 'தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்',
    'auth.accountCreated': 'கணக்கு வெற்றிகரமாக உருவாக்கப்பட்டது',
    'auth.passwordReset': 'கடவுச்சொல் மீட்டமை இணைப்பு அனுப்பப்பட்டது',
    'auth.loginSuccess': 'உள்நுழைவு வெற்றிகரமானது',
    'auth.logoutSuccess': 'வெளியேறுதல் வெற்றிகரமானது',
    
    // Dashboard
    'dashboard.welcome': 'மீண்டும் வரவேற்கிறோம்',
    'dashboard.overview': 'கண்ணோட்டம்',
    'dashboard.totalUsers': 'மொத்த பயனர்கள்',
    'dashboard.activeCourses': 'செயலில் உள்ள பாடங்கள்',
    'dashboard.completionRate': 'முடிவு விகிதம்',
    'dashboard.revenue': 'வருமானம்',
    'dashboard.newSignups': 'புதிய பதிவுகள்',
    'dashboard.activeUsers': 'செயலில் உள்ள பயனர்கள்',
    'dashboard.recentActivity': 'சமீபத்திய செயல்பாடு',
    'dashboard.quickActions': 'விரைவு செயல்கள்',
    'dashboard.statistics': 'புள்ளிவிவரங்கள்',
    'dashboard.performance': 'செயல்திறன்',
    'dashboard.trends': 'போக்குகள்',
    
    // Courses
    'courses.myCourses': 'என் பாடங்கள்',
    'courses.allCourses': 'அனைத்து பாடங்கள்',
    'courses.createCourse': 'பாடம் உருவாக்கு',
    'courses.editCourse': 'பாடத்தை திருத்து',
    'courses.deleteCourse': 'பாடத்தை நீக்கு',
    'courses.viewCourse': 'பாடத்தை பார்',
    'courses.enrollCourse': 'பாடத்தில் சேர்',
    'courses.unenrollCourse': 'பாடத்திலிருந்து வெளியேறு',
    'courses.title': 'பாட தலைப்பு',
    'courses.description': 'பாட விளக்கம்',
    'courses.instructor': 'பயிற்சியாளர்',
    'courses.duration': 'காலம்',
    'courses.difficulty': 'சிரம நிலை',
    'courses.enrollment': 'சேர்க்கை',
    'courses.rating': 'மதிப்பீடு',
    'courses.beginner': 'ஆரம்பநிலை',
    'courses.intermediate': 'இடைநிலை',
    'courses.advanced': 'மேம்பட்ட',
    'courses.enrollCourse': 'சேர்க்கை',
    'courses.createCourse': 'பாடம் உருவாக்கு',
    
    // Calendar
    'calendar.myCalendar': 'என் காலெண்டர்',
    'calendar.today': 'இன்று',
    'calendar.addEvent': 'நிகழ்வு சேர்க்க',
    'calendar.editEvent': 'நிகழ்வு திருத்த',
    'calendar.eventTitle': 'நிகழ்வு தலைப்பு',
    'calendar.eventDescription': 'விளக்கம்',
    'calendar.eventDate': 'தேதி',
    'calendar.eventType': 'வகை',
    'calendar.upcomingEvents': 'வரவிருக்கும் நிகழ்வுகள்',
    'calendar.noEvents': 'வரவிருக்கும் நிகழ்வுகள் இல்லை',
    'calendar.month': 'மாதம்',
    'calendar.agenda': 'நிகழ்ச்சி நிரல்',
    'calendar.event': 'நிகழ்வு',
    'calendar.class': 'வகுப்பு',
    'calendar.quiz': 'வினாடி வினா',
    'calendar.assignment': 'பணி',
    'calendar.meeting': 'கூட்டம்',
    
    // Profile
    'profile.editProfile': 'சுயவிவரம் திருத்த',
    'profile.avatar': 'சுயவிவர படம்',
    'profile.uploadAvatar': 'புகைப்படம் பதிவேற்று',
    'profile.removeAvatar': 'அகற்று',
    'profile.personalInfo': 'தனிப்பட்ட தகவல்',
    'profile.changePassword': 'கடவுச்சொல் மாற்று',
    'profile.currentPassword': 'தற்போதைய கடவுச்சொல்',
    'profile.newPassword': 'புதிய கடவுச்சொல்',
    'profile.confirmNewPassword': 'புதிய கடவுச்சொல் உறுதிப்படுத்து',
    'profile.updateProfile': 'சுயவிவரம் புதுப்பி',
    'profile.updateSuccess': 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    
    // Common
    'common.all': 'அனைத்தும்',
    'common.view': 'பார்க்க',
    'common.edit': 'திருத்த',
    'common.delete': 'நீக்க',
    'common.create': 'உருவாக்க',
    'common.update': 'புதுப்பி',
    'common.title': 'தலைப்பு',
    'common.description': 'விளக்கம்',
    'common.language': 'மொழி',
    'common.todo': 'செய்ய வேண்டியவை',
    
    // Errors
    'error.required': 'இந்த புலம் தேவை',
    'error.invalidEmail': 'சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்',
    'error.passwordTooShort': 'கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்',
    'error.passwordMismatch': 'கடவுச்சொற்கள் பொருந்தவில்லை',
    'error.general': 'ஒரு பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.',
    'error.invalidFormat': 'தவறான கோப்பு வடிவம்',
    'error.fileTooLarge': 'கோப்பு அளவு மிக பெரியது (அதிகபட்சம் 5MB)',
    'error.fileUpload': 'கோப்பு பதிவேற்றம் தோல்வியடைந்தது',
    'courses.price': 'விலை',
    'courses.category': 'பிரிவு',
    'courses.tags': 'குறிச்சொற்கள்',
    'courses.thumbnail': 'சிறுபடம்',
    'courses.content': 'பாட உள்ளடக்கம்',
    'courses.lessons': 'பாடங்கள்',
    'courses.modules': 'தொகுதிகள்',
    'courses.progress': 'முன்னேற்றம்',
    'courses.completed': 'முடிந்தது',
    'courses.inProgress': 'முன்னேற்றத்தில்',
    'courses.notStarted': 'தொடங்கவில்லை',
    'courses.beginner': 'ஆரம்பநிலை',
    'courses.intermediate': 'இடைநிலை',
    'courses.advanced': 'மேம்பட்ட',
    'courses.free': 'இலவசம்',
    'courses.paid': 'கட்டணம்',
    'courses.published': 'வெளியிடப்பட்ட',
    'courses.draft': 'வரைவு',
    'courses.pending': 'அங்கீகாரம் நிலுவையில்',
    'courses.approved': 'அங்கீகரிக்கப்பட்ட',
    'courses.rejected': 'நிராகரிக்கப்பட்ட',
    'courses.enrollmentSuccess': 'பாடத்தில் வெற்றிகரமாக சேர்ந்தீர்கள்',
    'courses.enrollmentError': 'பாடத்தில் சேர்வதில் தோல்வி',
    'courses.createSuccess': 'பாடம் வெற்றிகரமாக உருவாக்கப்பட்டது',
    'courses.updateSuccess': 'பாடம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
    'courses.deleteSuccess': 'பாடம் வெற்றிகரமாக நீக்கப்பட்டது',
    'courses.deleteConfirm': 'இந்த பாடத்தை நீக்க விரும்புகிறீர்களா?',
    
    // Quiz
    'quiz.myQuizzes': 'என் வினாடி வினாக்கள்',
    'quiz.allQuizzes': 'அனைத்து வினாடி வினாக்கள்',
    'quiz.createQuiz': 'வினாடி வினா உருவாக்கு',
    'quiz.editQuiz': 'வினாடி வினாவை திருத்து',
    'quiz.deleteQuiz': 'வினாடி வினாவை நீக்கு',
    'quiz.startQuiz': 'வினாடி வினாவை தொடங்கு',
    'quiz.submitQuiz': 'வினாடி வினாவை சமர்ப்பி',
    'quiz.retakeQuiz': 'வினாடி வினாவை மீண்டும் எடு',
    'quiz.quizResults': 'வினாடி வினா முடிவுகள்',
    'quiz.questions': 'கேள்விகள்',
    'quiz.timeLimit': 'நேர வரம்பு',
    'quiz.attempts': 'முயற்சிகள்',
    'quiz.passingScore': 'தேர்ச்சி மதிப்பெண்',
    'quiz.score': 'மதிப்பெண்',
    'quiz.passed': 'தேர்ச்சி',
    'quiz.failed': 'தோல்வி',
    'quiz.completed': 'முடிந்தது',
    'quiz.inProgress': 'முன்னேற்றத்தில்',
    'quiz.notStarted': 'தொடங்கவில்லை',
    'quiz.timeRemaining': 'மீதமுள்ள நேரம்',
    'quiz.question': 'கேள்வி',
    'quiz.answer': 'பதில்',
    'quiz.correctAnswer': 'சரியான பதில்',
    'quiz.explanation': 'விளக்கம்',
    'quiz.nextQuestion': 'அடுத்த கேள்வி',
    'quiz.previousQuestion': 'முந்தைய கேள்வி',
    'quiz.reviewAnswers': 'பதில்களை மதிப்பாய்வு செய்',
    'quiz.submitConfirm': 'வினாடி வினாவை சமர்ப்பிக்க விரும்புகிறீர்களா?',
    
    // Users
    'users.allUsers': 'அனைத்து பயனர்கள்',
    'users.createUser': 'பயனர் உருவாக்கு',
    'users.editUser': 'பயனரை திருத்து',
    'users.deleteUser': 'பயனரை நீக்கு',
    'users.viewUser': 'பயனரை பார்',
    'users.activateUser': 'பயனரை செயல்படுத்து',
    'users.deactivateUser': 'பயனரை செயலிழக்கச் செய்',
    'users.firstName': 'முதல் பெயர்',
    'users.lastName': 'கடைசி பெயர்',
    'users.email': 'மின்னஞ்சல்',
    'users.role': 'பாத்திரம்',
    'users.status': 'நிலை',
    'users.lastActive': 'கடைசியாக செயலில்',
    'users.joinedDate': 'சேர்ந்த தேதி',
    'users.admin': 'நிர்வாகி',
    'users.teacher': 'ஆசிரியர்',
    'users.student': 'மாணவர்',
    'users.active': 'செயலில்',
    'users.inactive': 'செயலற்ற',
    'users.online': 'ஆன்லைன்',
    'users.offline': 'ஆஃப்லைன்',
    'users.createSuccess': 'பயனர் வெற்றிகரமாக உருவாக்கப்பட்டார்',
    'users.updateSuccess': 'பயனர் வெற்றிகரமாக புதுப்பிக்கப்பட்டார்',
    'users.deleteSuccess': 'பயனர் வெற்றிகரமாக நீக்கப்பட்டார்',
    'users.deleteConfirm': 'இந்த பயனரை நீக்க விரும்புகிறீர்களா?',
    
    // Profile
    'profile.myProfile': 'என் சுயவிவரம்',
    'profile.editProfile': 'சுயவிவரத்தை திருத்து',
    'profile.updateProfile': 'சுயவிவரத்தை புதுப்பி',
    'profile.changePassword': 'கடவுச்சொல்லை மாற்று',
    'profile.currentPassword': 'தற்போதைய கடவுச்சொல்',
    'profile.newPassword': 'புதிய கடவுச்சொல்',
    'profile.confirmNewPassword': 'புதிய கடவுச்சொல்லை உறுதிப்படுத்து',
    'profile.avatar': 'சுயவிவர படம்',
    'profile.uploadAvatar': 'அவதாரம் பதிவேற்று',
    'profile.removeAvatar': 'அவதாரம் நீக்கு',
    'profile.personalInfo': 'தனிப்பட்ட தகவல்',
    'profile.accountSettings': 'கணக்கு அமைப்புகள்',
    'profile.preferences': 'விருப்பத்தேர்வுகள்',
    'profile.updateSuccess': 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
    'profile.passwordChanged': 'கடவுச்சொல் வெற்றிகரமாக மாற்றப்பட்டது',
    
    // Calendar
    'calendar.myCalendar': 'என் காலெண்டர்',
    'calendar.addEvent': 'நிகழ்வு சேர்',
    'calendar.editEvent': 'நிகழ்வை திருத்து',
    'calendar.deleteEvent': 'நிகழ்வை நீக்கு',
    'calendar.viewEvent': 'நிகழ்வை பார்',
    'calendar.eventTitle': 'நிகழ்வு தலைப்பு',
    'calendar.eventDescription': 'நிகழ்வு விளக்கம்',
    'calendar.eventDate': 'நிகழ்வு தேதி',
    'calendar.eventTime': 'நிகழ்வு நேரம்',
    'calendar.eventType': 'நிகழ்வு வகை',
    'calendar.allDay': 'முழு நாள்',
    'calendar.reminder': 'நினைவூட்டல்',
    'calendar.repeat': 'மீண்டும்',
    'calendar.location': 'இடம்',
    'calendar.attendees': 'பங்கேற்பாளர்கள்',
    'calendar.class': 'வகுப்பு',
    'calendar.quiz': 'வினாடி வினா',
    'calendar.assignment': 'பணி',
    'calendar.meeting': 'கூட்டம்',
    'calendar.event': 'நிகழ்வு',
    'calendar.today': 'இன்று',
    'calendar.week': 'வாரம்',
    'calendar.month': 'மாதம்',
    'calendar.year': 'ஆண்டு',
    'calendar.agenda': 'நிகழ்ச்சி நிரல்',
    'calendar.upcomingEvents': 'வரவிருக்கும் நிகழ்வுகள்',
    'calendar.noEvents': 'நிகழ்வுகள் எதுவும் திட்டமிடப்படவில்லை',
    'calendar.createSuccess': 'நிகழ்வு வெற்றிகரமாக உருவாக்கப்பட்டது',
    'calendar.updateSuccess': 'நிகழ்வு வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
    'calendar.deleteSuccess': 'நிகழ்வு வெற்றிகரமாக நீக்கப்பட்டது',
    'calendar.deleteConfirm': 'இந்த நிகழ்வை நீக்க விரும்புகிறீர்களா?',
    
    // Notifications
    'notifications.allNotifications': 'அனைத்து அறிவிப்புகள்',
    'notifications.markAsRead': 'படித்ததாக குறி',
    'notifications.markAllAsRead': 'அனைத்தையும் படித்ததாக குறி',
    'notifications.deleteNotification': 'அறிவிப்பை நீக்கு',
    'notifications.clearAll': 'அனைத்தையும் அழி',
    'notifications.unread': 'படிக்காத',
    'notifications.read': 'படித்த',
    'notifications.info': 'தகவல்',
    'notifications.success': 'வெற்றி',
    'notifications.warning': 'எச்சரிக்கை',
    'notifications.error': 'பிழை',
    'notifications.newCourse': 'புதிய பாடம் கிடைக்கிறது',
    'notifications.quizReminder': 'வினாடி வினா நினைவூட்டல்',
    'notifications.assignmentDue': 'பணி காலாவதி',
    'notifications.gradePosted': 'மதிப்பெண் இடுகையிடப்பட்டது',
    'notifications.messageReceived': 'செய்தி பெறப்பட்டது',
    'notifications.courseCompleted': 'பாடம் முடிந்தது',
    'notifications.certificateReady': 'சான்றிதழ் தயார்',
    'notifications.systemMaintenance': 'கணினி பராமரிப்பு',
    'notifications.noNotifications': 'அறிவிப்புகள் இல்லை',
    'notifications.pushEnabled': 'புஷ் அறிவிப்புகள் இயக்கப்பட்டன',
    'notifications.pushDisabled': 'புஷ் அறிவிப்புகள் முடக்கப்பட்டன',
    
    // Messages
    'messages.allMessages': 'அனைத்து செய்திகள்',
    'messages.newMessage': 'புதிய செய்தி',
    'messages.sendMessage': 'செய்தி அனுப்பு',
    'messages.replyMessage': 'பதில் அனுப்பு',
    'messages.forwardMessage': 'முன்னோக்கி அனுப்பு',
    'messages.deleteMessage': 'செய்தியை நீக்கு',
    'messages.markAsRead': 'படித்ததாக குறி',
    'messages.markAsUnread': 'படிக்காததாக குறி',
    'messages.searchMessages': 'செய்திகளை தேடு',
    'messages.recipient': 'பெறுநர்',
    'messages.subject': 'பொருள்',
    'messages.message': 'செய்தி',
    'messages.attachment': 'இணைப்பு',
    'messages.sent': 'அனுப்பப்பட்ட',
    'messages.received': 'பெறப்பட்ட',
    'messages.draft': 'வரைவு',
    'messages.trash': 'குப்பை',
    'messages.inbox': 'இன்பாக்ஸ்',
    'messages.outbox': 'அவுட்பாக்ஸ்',
    'messages.compose': 'எழுது',
    'messages.noMessages': 'செய்திகள் இல்லை',
    'messages.sendSuccess': 'செய்தி வெற்றிகரமாக அனுப்பப்பட்டது',
    'messages.deleteSuccess': 'செய்தி வெற்றிகரமாக நீக்கப்பட்டது',
    
    // Analytics
    'analytics.overview': 'பகுப்பாய்வு கண்ணோட்டம்',
    'analytics.userAnalytics': 'பயனர் பகுப்பாய்வு',
    'analytics.courseAnalytics': 'பாட பகுப்பாய்வு',
    'analytics.quizAnalytics': 'வினாடி வினா பகுப்பாய்வு',
    'analytics.performanceAnalytics': 'செயல்திறன் பகுப்பாய்வு',
    'analytics.engagementAnalytics': 'ஈடுபாடு பகுப்பாய்வு',
    'analytics.revenueAnalytics': 'வருமான பகுப்பாய்வு',
    'analytics.exportReport': 'அறிக்கை ஏற்றுமதி',
    'analytics.generateReport': 'அறிக்கை உருவாக்கு',
    'analytics.customReport': 'தனிப்பயன் அறிக்கை',
    'analytics.dateRange': 'தேதி வரம்பு',
    'analytics.lastWeek': 'கடந்த வாரம்',
    'analytics.lastMonth': 'கடந்த மாதம்',
    'analytics.lastQuarter': 'கடந்த காலாண்டு',
    'analytics.lastYear': 'கடந்த ஆண்டு',
    'analytics.customRange': 'தனிப்பயன் வரம்பு',
    
    // Certificates
    'certificates.myCertificates': 'என் சான்றிதழ்கள்',
    'certificates.allCertificates': 'அனைத்து சான்றிதழ்கள்',
    'certificates.viewCertificate': 'சான்றிதழ் பார்',
    'certificates.downloadCertificate': 'சான்றிதழ் பதிவிறக்கு',
    'certificates.shareCertificate': 'சான்றிதழ் பகிர்',
    'certificates.verifyCertificate': 'சான்றிதழ் சரிபார்',
    'certificates.certificateId': 'சான்றிதழ் ஐடி',
    'certificates.issuedDate': 'வழங்கப்பட்ட தேதி',
    'certificates.expiryDate': 'காலாவதி தேதி',
    'certificates.issuer': 'வழங்குநர்',
    'certificates.recipient': 'பெறுநர்',
    'certificates.course': 'பாடம்',
    'certificates.grade': 'தரம்',
    'certificates.valid': 'செல்லுபடியாகும்',
    'certificates.expired': 'காலாவதியானது',
    'certificates.revoked': 'ரத்து செய்யப்பட்டது',
    'certificates.noCertificates': 'சான்றிதழ்கள் கிடைக்கவில்லை',
    
    // Settings
    'settings.generalSettings': 'பொது அமைப்புகள்',
    'settings.accountSettings': 'கணக்கு அமைப்புகள்',
    'settings.privacySettings': 'தனியுரிமை அமைப்புகள்',
    'settings.notificationSettings': 'அறிவிப்பு அமைப்புகள்',
    'settings.languageSettings': 'மொழி அமைப்புகள்',
    'settings.themeSettings': 'தீம் அமைப்புகள்',
    'settings.securitySettings': 'பாதுகாப்பு அமைப்புகள்',
    'settings.systemSettings': 'கணினி அமைப்புகள்',
    'settings.saveSettings': 'அமைப்புகளை சேமி',
    'settings.resetSettings': 'அமைப்புகளை மீட்டமை',
    'settings.exportSettings': 'அமைப்புகளை ஏற்றுமதி',
    'settings.importSettings': 'அமைப்புகளை இறக்குமதி',
    'settings.lightMode': 'ஒளி பயன்முறை',
    'settings.darkMode': 'இருள் பயன்முறை',
    'settings.autoMode': 'தானியங்கி பயன்முறை',
    'settings.emailNotifications': 'மின்னஞ்சல் அறிவிப்புகள்',
    'settings.pushNotifications': 'புஷ் அறிவிப்புகள்',
    'settings.smsNotifications': 'SMS அறிவிப்புகள்',
    'settings.twoFactorAuth': 'இரு-காரணி அங்கீகாரம்',
    'settings.sessionTimeout': 'அமர்வு காலாவதி',
    'settings.dataRetention': 'தரவு தக்கவைப்பு',
    'settings.privacyMode': 'தனியுரிமை பயன்முறை',
    'settings.publicProfile': 'பொது சுயவிவரம்',
    'settings.showOnlineStatus': 'ஆன்லைன் நிலையை காட்டு',
    'settings.allowMessages': 'செய்திகளை அனுமதி',
    'settings.settingsUpdated': 'அமைப்புகள் வெற்றிகரமாக புதுப்பிக்கப்பட்டன',
    
    // Errors
    'error.general': 'ஒரு பிழை ஏற்பட்டது',
    'error.network': 'நெட்வொர்க் பிழை',
    'error.server': 'சர்வர் பிழை',
    'error.notFound': 'கிடைக்கவில்லை',
    'error.unauthorized': 'அங்கீகரிக்கப்படாத',
    'error.forbidden': 'தடைசெய்யப்பட்ட',
    'error.validation': 'சரிபார்ப்பு பிழை',
    'error.timeout': 'கோரிக்கை காலாவதி',
    'error.fileUpload': 'கோப்பு பதிவேற்ற பிழை',
    'error.fileTooLarge': 'கோப்பு மிகப் பெரியது',
    'error.invalidFormat': 'தவறான வடிவம்',
    'error.required': 'இந்த புலம் தேவை',
    'error.invalidEmail': 'தவறான மின்னஞ்சல் முகவரி',
    'error.passwordTooShort': 'கடவுச்சொல் மிகக் குறுகியது',
    'error.passwordMismatch': 'கடவுச்சொற்கள் பொருந்தவில்லை',
    'error.tryAgain': 'தயவுசெய்து மீண்டும் முயற்சிக்கவும்',
    'error.contactSupport': 'தயவுசெய்து ஆதரவைத் தொடர்பு கொள்ளவும்',
    
    // Success Messages
    'success.saved': 'வெற்றிகரமாக சேமிக்கப்பட்டது',
    'success.updated': 'வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
    'success.deleted': 'வெற்றிகரமாக நீக்கப்பட்டது',
    'success.created': 'வெற்றிகரமாக உருவாக்கப்பட்டது',
    'success.uploaded': 'வெற்றிகரமாக பதிவேற்றப்பட்டது',
    'success.downloaded': 'வெற்றிகரமாக பதிவிறக்கப்பட்டது',
    'success.sent': 'வெற்றிகரமாக அனுப்பப்பட்டது',
    'success.completed': 'வெற்றிகரமாக முடிக்கப்பட்டது',
    'success.enrolled': 'வெற்றிகரமாக சேர்க்கப்பட்டது',
    'success.unenrolled': 'வெற்றிகரமாக நீக்கப்பட்டது',
    'success.activated': 'வெற்றிகரமாக செயல்படுத்தப்பட்டது',
    'success.deactivated': 'வெற்றிகரமாக செயலிழக்கச் செய்யப்பட்டது',
    'success.verified': 'வெற்றிகரமாக சரிபார்க்கப்பட்டது',
    'success.published': 'வெற்றிகரமாக வெளியிடப்பட்டது',
    'success.unpublished': 'வெற்றிகரமாக வெளியீடு நிறுத்தப்பட்டது',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('lms_language') as Language;
    if (savedLanguage && ['en', 'hi', 'ta'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('lms_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage: handleSetLanguage,
    t,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};